
# 是否打开 undertow 日志，默认为 false
server:
  undertow:
    accesslog:
      enabled: false
  port: 8282
  servlet:
    context-path: '/undertow'
# 指定工作者线程的 I/0 线程数，默认为 2 或者 CPU 的个数
#server.undertow.io-threads=
# 指定工作者线程个数，默认为 I/O 线程个数的 8 倍
#server.undertow.worker-threads=
# 设置 HTTP POST 内容的最大长度，默认不做限制
#server.undertow.max-http-post-size=0