server:
  port: 8281
  servlet:
    context-path: '/tomcat'
  tomcat:
    max-threads: 200
    min-spare-threads: 50

spring:
  application:
    name: spring-boot-web-tomcat-container
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      management:
        context-path: /tomcat/actuator
    health-check-url: http://localhost:${server.port}/tomcat/actuator/health
    status-page-url: http://localhost:${server.port}/tomcat/actuator/info
    home-page-url: http://localhost:${server.port}/
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" #配置这个将监控所有的信息
  endpoint:
    health:
      show-details: ALWAYS