server:
  port: 8777

spring:
  application:
    name: spring-boot-quartz
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    name: spring-boot-quartz
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/spring_boot_quartz?characterEncoding=UTF-8&allowMultiQueries=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: root
      minimum-idle: 10 #连接池中允许的最小连接数
      maximum-pool-size: 50 #连接池中允许的最大连接数。缺省值：10
      connection-timeout: 30000 #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      idle-timeout: 600000 #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      max-lifetime: 1800000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟
  resources:
    static-locations: classpath:/static/


#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: zzq.entity
