
# 是否打开 undertow 日志，默认为 false
server:
  undertow:
    accesslog:
      enabled: false
    # HTTP POST请求最大的大小
    max-http-post-size: 0
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 16
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 128
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

  port: 8282
  servlet:
    context-path: '/undertow'

spring:
  application:
    name: spring-boot-web-undertow-container
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      management:
        context-path: /undertow/actuator
    health-check-url: http://localhost:${server.port}/undertow/actuator/health
    status-page-url: http://localhost:${server.port}/undertow/actuator/info
    home-page-url: http://localhost:${server.port}/
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" #配置这个将监控所有的信息
  endpoint:
    health:
      show-details: ALWAYS