spring:
  application:
    name: zuul
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    name: zzq_oauth2
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/zzq_oauth2?characterEncoding=UTF-8&allowMultiQueries=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

server:
  port: 7777
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
feign:
  hystrix:
    enabled: true