spring:
  application:
    name: zuul
  main:
    allow-bean-definition-overriding: true
server:
  port: 8666
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
zuul:
  routes:
    admin:
      path: /admin/**
      serviceId: admin
    oauth2:
      path: /oauth2/**
      serviceId: aouth2
    resource:
      path: /resource/**
      serviceId: resource
feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      client-id: client1
      client-secret: 123456
      access-token-uri: http://localhost:${server.port}/oauth2/oauth/token
      user-authorization-uri: http://localhost:${server.port}/oauth2/oauth/authorize
      scope: read
      use-current-uri: false
      registered-redirect-uri: https://www.baidu.com
    resource:
      prefer-token-info: false
      user-info-uri: http://localhost:${server.port}/oauth2/user