spring:
  application:
    name: zuul
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
server:
  port: 8666
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

zuul:
  routes:
    back:
      path: /admin/**
      serviceId: admin