spring:
  application:
    name: zuul
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    name: zzq_oauth2
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/zzq_oauth2?characterEncoding=UTF-8&allowMultiQueries=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

server:
  port: 8666

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

zuul:
  routes:
    admin:
      path: /admin/**
      serviceId: admin
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 10000

securityign:
  hystrix:
    enabled: true

feign:
  hystrix:
    enabled: true

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 5000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 3000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #断路器超时时间，默认1000ms

#服务监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

